#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Проверяем линтинг
if ! bun run lint; then
  echo "Linting failed. Please fix the issues before pushing." >&2
  exit 1
fi

# Проверяем форматирование
if ! bun run format; then
  echo "Formatting failed. Please fix the issues before pushing." >&2
  exit 1
fi

# Проверяем сборку
if ! bun run build; then
  echo "Build failed. Please fix the issues before pushing." >&2
  exit 1
fi